package org.campbelll.android.moviebrowser;

/**
 * Implementers of this interface will handle events generated by MovieListFragment list selections.
 *
 * Created by campbell on 12/05/2015.
 */
public interface MovieSelectionListener {
    public void onMovieSelected(Movie movie);
}
